config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  devise_for :users, skip: [:registrations]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :customers do
    resources :addresses
  end

  resources :products do
    collection do
      get :enableds
      get :disableds
    end

    member do
      patch :enable
      patch :disable
    end
  end

  root "products#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders, dependent: :restrict_with_error
  has_many :addresses, as: :addressable, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :email, email: true, allow_blank: true

  def full_name
    first_name + ' ' + last_name
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :find_model, except: %w(index new create)

  def index
    @customers = Customer.all.paginate page: params[:page]

    respond_to do |format|
      format.html{ }

      format.json do
        render json: { customers: @customers, total_entries: Customer.count }
      end
    end
  end

  def new
    @customer = Customer.new
    respond_to do |format|
      format.html{ }
      format.json do
        render json: @customer
      end
    end
  end

  def create
    @customer = Customer.new permit_params
    if @customer.save
      respond_to do |format|
        format.html do
          flash[:success] = "Votre enregistrement a été sauvegardé"
          redirect_to customers_path
        end
        format.json do
          render json: @customer
        end
      end
    else
      respond_to do |format|
        format.html do
          render :new
        end
        format.json do
          render json: @customer.errors, status: 406
        end
      end
    end
  end

  def edit
    @customer = Customer.find params[:id]
    respond_to do |format|
      format.html{ }
      format.json do
        render json: @customer
      end
    end
  end

  def update
    if @customer.update permit_params
      respond_to do |format|
        format.html do
          flash[:success] = "Votre enregistrement a été sauvegardé"
          redirect_to customers_path
        end
        format.json do
          render json: @customer
        end
      end
    else
      respond_to do |format|
        format.html do
          render :edit
        end
        format.json do
          render json: @customer.errors, status: 406
        end
      end
    end
  end

  def show
    respond_to do |format|
      format.html{ }
      format.json do
        render json: @customer
      end
    end
  end


  def destroy
    respond_to do |format|
      if @customer.destroy
        format.html do
          flash[:success] = "Elément supprimé"
          redirect_to customers_path
        end
        format.json do
            head :ok
        end
      else
        format.html do
          flash[:error] = "Elément non supprimé: #{@customer.errors.full_messages.join(', ')}"
          redirect_to customers_path
        end
        format.json do
          render json: @customer.errors, status: 406
        end
      end
    end
  end

  private
    def find_model
      @customer = Customer.find params[:id]
    end

    def permit_params
      params.require(:customer).permit(:first_name, :last_name, :email)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.haml
%tr
  %td= customer.id
  %td= link_to customer.first_name, edit_customer_path(customer), title: 'Modifier le client'
  %td= customer.last_name
  %td= mail_to customer.email
  %td
    = link_to customer_addresses_path(customer), class: 'btn btn-sm btn-primary' do
      %i.fas.fa-building
      Adresses
    &nbsp;
    = link_to customer_path(customer), data: { turbo_method: :delete, turbo_confirm: t('ui.confirm_destroy')}, class: 'btn btn-sm btn-danger' do
      %i.fa.fa-trash
      = t("ui.destroy")

app/views/customers/_form.html.haml
.card
  .card-header

  .card-body
    .row
      .col-6= f.input :first_name
      .col-6= f.input :last_name
    .row
      .col-6= f.input :email
      .col-6
  .card-footer
    .row
      .col-12.text-right
        = f.submit "Enregistrer", class: "btn btn-success btn-sm"

app/views/customers/edit.html.haml
- content_for :page_title do
  %h1= t('customers.edit.title', label: @customer.full_name)

.row
  .col-12
    = simple_form_for @customer, url: customer_url(@customer), html: { method: :patch }, data: { turbo: false } do |f|
      = render partial: 'form', locals: { f: f }

app/views/customers/index.html.haml
- content_for :page_title do
  %h1= t('customers.index.title')
- content_for :subtitle do
  %p= t('customers.index.subtitle')

.row.mb-4
  .col-12.text-right
    /= link_to "Nouveau produit", new_customer_url, class: "btn btn-primary btn-sm"
    = link_to new_customer_url, class: "btn btn-primary btn-sm" do
      %i.fa.fa-plus
      = t("ui.new")
.row
  .col-12
    .card
      .card-header
        %h3.card-title= t('customers.index.title')
      .card-body
        %table.table.table-bordered.table-hover
          %thead
            %tr
              %th ID
              %th= t('activerecord.attributes.customer.first_name')
              %th= t('activerecord.attributes.customer.last_name')
              %th= t('activerecord.attributes.customer.email')
              %th
          %tbody
            = render partial: 'customer', collection: @customers

      .card-footer
        .row
          .col-12
            = will_paginate @customers

app/views/customers/new.html.haml
- content_for :page_title do
  %h1 Nouveau client

.row
  .col-12
    = simple_form_for @customer, url: customers_url, data: { turbo: false } do |f|
      = render partial: 'form', locals: { f: f }