config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  devise_for :users, skip: [:registrations]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :customers do
    resources :addresses
  end

  resources :products do
    collection do
      get :enableds
      get :disableds
    end

    member do
      patch :enable
      patch :disable
    end
  end

  root "products#index"
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :find_customer
  before_action :find_model, except: %w(index new create)

  def index
    @addresses = @customer.addresses.all.paginate page: params[:page]

    respond_to do |format|
      format.html{ }

      format.json do
        render json: { addresses: @addresses, total_entries: Address.count }
      end
    end
  end

  def new
    @address = @customer.addresses.new
    respond_to do |format|
      format.html{ }
      format.json do
        render json: @address
      end
    end
  end

  def create
    @address = @customer.addresses.new permit_params
    if @address.save
      respond_to do |format|
        format.html do
          flash[:success] = "Votre enregistrement a été sauvegardé"
          redirect_to customer_addresses_path(@customer)
        end
        format.json do
          render json: @address
        end
      end
    else
      respond_to do |format|
        format.html do
          render :new
        end
        format.json do
          render json: @address.errors, status: 406
        end
      end
    end
  end

  def edit
    respond_to do |format|
      format.html{ }
      format.json do
        render json: @address
      end
    end
  end

  def update
    if @address.update permit_params
      respond_to do |format|
        format.html do
          flash[:success] = "Votre enregistrement a été sauvegardé"
          redirect_to customer_addresses_path(@customer)
        end
        format.json do
          render json: @address
        end
      end
    else
      respond_to do |format|
        format.html do
          render :edit
        end
        format.json do
          render json: @address.errors, status: 406
        end
      end
    end
  end

  def show
    respond_to do |format|
      format.html{ }
      format.json do
        render json: @address
      end
    end
  end


  def destroy
    respond_to do |format|
      if @address.destroy
        format.html do
          flash[:success] = "Elément supprimé"
          redirect_to customer_addresses_path(@customer)
        end
        format.json do
            head :ok
        end
      else
        format.html do
          flash[:error] = "Elément non supprimé: #{@address.errors.full_messages.join(', ')}"
          redirect_to customer_addresses_path(@customer)
        end
        format.json do
          render json: @address.errors, status: 406
        end
      end
    end
  end

  private
    def find_customer
      @customer = Customer.find params[:customer_id]
    end

    def find_model
      @address = @customer.addresses.find params[:id]
    end

    def permit_params
      params.require(:address).permit(:street, :postal_code, :city)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_address.html.haml
%tr
  %td= address.id
  %td= link_to address.street, edit_customer_address_path(@customer,address), title: 'Modifier une adresse'
  %td= address.postal_code
  %td= mail_to address.city
  %td
    = link_to customer_address_path(@customer,address), data: { turbo_method: :delete, turbo_confirm: t('ui.confirm_destroy')}, class: 'btn btn-sm btn-danger' do
      %i.fa.fa-trash
      = t("ui.destroy")

app/views/addresses/_form.html.haml
.card
  .card-header

  .card-body
    .row
      .col-12= f.input :street
    .row
      .col-6= f.input :postal_code
      .col-6= f.input :city

  .card-footer
    .row
      .col-12.text-right
        = f.submit "Enregistrer", class: "btn btn-success btn-sm"

app/views/addresses/edit.html.haml
- content_for :page_title do
  %h1= t('addresses.edit.title', label: @address.street)

.row
  .col-12
    = simple_form_for @address, url: customer_address_url(@customer, @address), html: { method: :patch }, data: { turbo: false } do |f|
      = render partial: 'form', locals: { f: f }

app/views/addresses/index.html.haml
- content_for :page_title do
  %h1= t('addresses.index.title')
- content_for :subtitle do
  %p= t('addresses.index.subtitle')

.row.mb-4
  .col-12.text-right
    /= link_to "Nouveau produit", new_address_url, class: "btn btn-primary btn-sm"
    = link_to new_customer_address_url(@customer), class: "btn btn-primary btn-sm" do
      %i.fa.fa-plus
      = t("ui.new")
.row
  .col-12
    .card
      .card-header
        %h3.card-title= t('addresses.index.title')
      .card-body
        %table.table.table-bordered.table-hover
          %thead
            %tr
              %th ID
              %th= t('activerecord.attributes.address.street')
              %th= t('activerecord.attributes.address.postal_code')
              %th= t('activerecord.attributes.address.city')
              %th
          %tbody
            = render partial: 'address', collection: @addresses

      .card-footer
        .row
          .col-12
            = will_paginate @addresses

app/views/addresses/new.html.haml
- content_for :page_title do
  %h1 Nouvelle adresse

.row
  .col-12
    = simple_form_for @address, url: customer_addresses_url(@customer), data: { turbo: false } do |f|
      = render partial: 'form', locals: { f: f }