config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  devise_for :users, skip: [:registrations]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :customers do
    resources :addresses
  end

  resources :products do
    collection do
      get :enableds
      get :disableds
    end

    member do
      patch :enable
      patch :disable
    end
  end

  root "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items, dependent: :restrict_with_error
  # has_many :order_items, dependent: :restrict_with_exception

  has_many :category_products, dependent: :destroy
  has_many :categories, through: :category_products

  validates :label, presence: true
  validates :unit_price_et, presence: true
  validates :vat, presence: true
  validates :unit_price_et, numericality: true
  validates :vat, numericality: true

  default_scope -> { order('label ASC') }
  scope :disableds, -> { where(state: 'disabled') }
  scope :enableds, -> { where(state: 'enabled') }

  state_machine :state, initial: :enabled do
    event :enable do
      transition disabled: :enabled
    end

    event :disable do
      transition enabled: :disabled
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_model, except: %w(index new create enableds disableds)

  def index
    @products = Product.all.paginate page: params[:page]

    respond_to do |format|
      format.html{ }

      format.json do
        render json: { products: @products, total_entries: Product.count }
      end
    end
  end

  def enableds
    @products = Product.enableds.paginate page: params[:page]

    respond_to do |format|
      format.html{ }

      format.json do
        render json: { products: @products, total_entries: Product.enableds.count }
      end
    end
  end

  def disableds
    @products = Product.disableds.paginate page: params[:page]

    respond_to do |format|
      format.html{ }

      format.json do
        render json: { products: @products, total_entries: Product.disableds.count }
      end
    end
  end

  def new
    @product = Product.new
    respond_to do |format|
      format.html{ }
      format.json do
        render json: @product
      end
    end
  end

  def create
    @product = Product.new permit_params
    if @product.save
      ActionCable.server.broadcast "product_channel", { message: "Un nouveau produit a été ajouté" }
      respond_to do |format|
        format.html do
          flash[:success] = "Votre enregistrement a été sauvegardé"
          redirect_to products_path
        end
        format.json do
          render json: @product
        end
      end
    else
      respond_to do |format|
        format.html do
          render :new
        end
        format.json do
          render json: @product.errors, status: 406
        end
      end
    end
  end

  def edit
    @product = Product.find params[:id]
    respond_to do |format|
      format.html{ }
      format.json do
        render json: @product
      end
    end
  end

  def update
    if @product.update permit_params
      respond_to do |format|
        format.html do
          flash[:success] = "Votre enregistrement a été sauvegardé"
          redirect_to products_path
        end
        format.json do
          render json: @product
        end
      end
    else
      respond_to do |format|
        format.html do
          render :edit
        end
        format.json do
          render json: @product.errors, status: 406
        end
      end
    end
  end

  def show
    respond_to do |format|
      format.html{ }
      format.json do
        render json: @product
      end
    end
  end

  def disable
    respond_to do |format|
      format.html{ }
      format.json do
        if @product.disable
          render json: @product
        else
          render json: @product.errors, status: 406
        end
      end
    end
  end

  def enable
    respond_to do |format|
      format.html{ }
      format.json do
        if @product.enable
          render json: @product
        else
          render json: @product.errors, status: 406
        end
      end
    end
  end

  def destroy
    respond_to do |format|
      if @product.destroy
        format.html do
          flash[:success] = "Elément supprimé"
          redirect_to products_path
        end
        format.json do
            head :ok
        end
      else
        format.html do
          flash[:error] = "Elément non supprimé: #{@product.errors.full_messages.join(', ')}"
          redirect_to products_path
        end
        format.json do
          render json: @product.errors, status: 406
        end
      end
    end
  end

  private
    def find_model
      @product = Product.find params[:id]
    end

    def permit_params
      params.require(:product).permit(:label, :unit_price_et, :vat)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
.card
  .card-header

  .card-body
    .row
      .col-12= f.input :label
    .row
      .col-6= f.input :unit_price_et
      .col-6= f.input :vat
  .card-footer
    .row
      .col-12.text-right
        = f.submit "Enregistrer", class: "btn btn-success btn-sm"

app/views/products/_product.html.haml
%tr
  %td= product.id
  %td= link_to product.label, edit_product_path(product), title: 'Modifier le produit'
  %td= product.unit_price_et
  %td
    = link_to product_path(product), data: { turbo_method: :delete, turbo_confirm: t('ui.confirm_destroy')}, class: 'btn btn-sm btn-danger' do
      %i.fa.fa-trash
      = t("ui.destroy")

app/views/products/edit.html.haml
- content_for :page_title do
  %h1= t('products.edit.title', label: @product.label)

.row
  .col-12
    = simple_form_for @product, url: product_url(@product), html: { method: :patch }, data: { turbo: false } do |f|
      = render partial: 'form', locals: { f: f }

app/views/products/index.html.haml
= turbo_page_requires_reload

- content_for :page_title do
  %h1= t('products.index.title')
- content_for :subtitle do
  %p= t('products.index.subtitle')

.row.mb-4
  .col-12.text-right
    /= link_to "Nouveau produit", new_product_url, class: "btn btn-primary btn-sm"
    = link_to new_product_url, class: "btn btn-primary btn-sm", data: { turbo_frame: "modal" } do
      %i.fa.fa-plus
      = t("ui.new")
.row
  .col-12
    .card
      .card-header
        %h3.card-title= t('products.index.title')
      .card-body
        %table.table.table-bordered.table-hover
          %thead
            %tr
              %th ID
              %th= t('activerecord.attributes.product.label')
              %th= t('activerecord.attributes.product.unit_price_et')
              %th
          %tbody
            = render partial: 'product', collection: @products

      .card-footer
        .row
          .col-12
            = will_paginate @products

app/views/products/new.html.haml
= render 'shared/modal', title: "Nouveau produit" do
  = simple_form_for @product, url: products_url do |f|
    = render partial: 'form', locals: { f: f }